### ISSUE TITLE
MVP and Schema Issues

### ISSUE THREAD

**Issue by OhBall** [samfortunato/IndividualCylinder#1]
- [x] MVPs are not fleshed out. There should be at least 3 bullet points for each MVP.

- [x] Instead of having a separate table for `video_likes` and `comment_likes`, you should have a single table for just `likes`. This table can then have a polymorphic association to both videos and comments.
       - This table should have an index and uniqueness on the combination of `[user_id, likable_id, likable_type]`. This will make sure that someone cannot like something multiple time.

- [x] Because you’re going to have a separate table for likes, it’s unreasonable to also have a column for likes and dislikes. Instead, you can just use ActiveRecord to count the number of `likes` that are an positive or negative.

- [x] I’m not sure what the `video_page_url` of the `videos` table is meant to represent. If it’s the alphanumeric string associated with a video to actually view the “show” page for it, you’ll just use the `id` of the video.

- [x] If you’re going to include things like `license` for your videos, don’t spend too much time worrying about it. Feel free to just have a default that every video has. Same thing goes for other minutia columns.

- [x] You will want to have some sort of thumbnail for videos.

- [x] Chungus not big enough

**Comment by samfortunato** [comment]
Hey Oliver,

Apologies. Thought only schema was due last night.

I'm a little unclear on the whole polymorphic association thing. Do I have
to create a separate table for that? I consolidated the likes into one
table schema, but I'm not sure what columns I need.

Not sure which table you're referring to about the likes/dislikes
distinction? I wanted to have this because you can see likes AND dislikes
on YouTube, so it's not just an increment/decrement total likes thing.
Unless you're saying I can get those totals from a `like_type` column in
likes or something?

Think I got everything else. Also, was thinking of doing a Big Chungus
let's play as an example video for my project, with some Elite Gamer
Commentary™. just gotta dust off the video capture gear
